
import Header from "@/components/Header";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative ">
        <div className="w-full min-h-screen overflow-hidden">
        <Header/>
        {children}

        </div>
      </body>
    </html>
  );
}
